name: 08 - testing selfhosted runner

on:
    push:
        branches: ["*"]

jobs:
    node-test:
        runs-on: self-hosted
        steps:
            - name: checkout the code
              uses: actions/checkout@v7
            - name: run my application
              run: node app.js
            - name: Use IAM role and List buckets
              run: |
                aws s3 ls
                aws s3 ls s3://suman-bkt-gha
                aws s3 ls s3://shiva-bkt-gha
                aws s3 ls s3://chotu-bkt-gha
