name: 10 - S3 create using Input option

on:
    workflow_dispatch:
        inputs:
            bucket-name: 
                description: 'Enter Bucket name you would like to create'
                required: true
                type: string

permissions:
    id-token: write
    contents: read

jobs:
    create-bucket:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.3.0
              with:
                aws-region: ${{ vars.AWS_REGION }}
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            - name: use OIDC and create bucket
              run: |
                aws s3 mb s3://${{ github.event.inputs.bucket-name }} --region ${{ vars.AWS_REGION }}
                aws s3 ls